[versions]
kotlin = "2.2.0"
freemarker = "2.3.34"
junit = "6.0.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
freemarker = { group = "org.freemarker", name = "freemarker", version.ref = "freemarker" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }

[bundles]
implementation = ["freemarker"]
testImplementation = ["junit-platform-launcher", "junit-jupiter", "junit-jupiter-api", "junit-jupiter-params"]
