[versions]
kotlin = "2.2.0"
freemarker = "2.3.34"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
freemarker = { group = "org.freemarker", name = "freemarker", version.ref = "freemarker" }

[bundles]
implementation = ["freemarker"]
